apiVersion: apps/v1
kind: Deployment
metadata:
  name: ymir-front
spec:
  replicas: 3
  revisionHistorysLimit: 3
  selector:
    matchLabels:
      app: ymir-front
  template:
    metadata:
      labels:
        app: ymir-front
    spec:
      containers:
      - image: ablts0/ymir-front:latest
        name: ymir-front
        ports:
        - containerPort: 80
